services:
  # default configuration for services in *this* file
  _defaults:
    autowire: true      # Automatically injects dependencies in your services.
    autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
    public: false

  Tourze\WechatPayProfitShareBundle\Controller\:
    resource: '../../Controller/'
  Tourze\WechatPayProfitShareBundle\Repository\:
    resource: '../../Repository/'
  Tourze\WechatPayProfitShareBundle\Service\:
    resource: '../../Service/'
    public: true
  Tourze\WechatPayProfitShareBundle\Command\:
    resource: '../../Command/'
